### PR TITLE
GPU Flow - Harris Corner Fix

### PR DESCRIPTION
**Pull request by hansely**
-Harris corner fix for gpu
-Harris test gdf fix

### CODE REVIEW

**Comment by kiritigowda** [comment]
@hansely does this still break other tests?

**Comment by hansely** [comment]
@kiritigowda Yes. I had a meeting with Rajy and was going to ask you about this. Can we have a quick meeting tomorrow?

**Comment by kiritigowda** [comment]
@hansely can you resolve the merge conflicts?

**Comment by hansely** [comment]
@kiritigowda This is not ready yet. I'll solve it when ready.

**Pull request closed without merging**
