### PR TITLE
GPU Flow - Bug Fixes

### PR DESCRIPTION
**Pull request by LakshmiKumar23**
- GraphROI.Simple 
- Graph.GraphState 
- Threshold.OnRandom/4/Graph/BINARY/U8/U8
- Threshold.OnRandom/5/Graph/BINARY/S16/U8
- Threshold.OnRandom/7/Graph/RANGE/S16/U8
- vxMapRemapPatch.MapRandomRemap

### CODE REVIEW

**Comment by kiritigowda** [comment]
Is this ready to be merged? @LakshmiKumar23 did you run the latest CTS.

**Comment by LakshmiKumar23** [comment]
> Is this ready to be merged? @LakshmiKumar23 did you run the latest CTS.

@kiritigowda Ran with latest CTS. Ready to be merged with 2 more fixes

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you resolve the conflicts?

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 can you resolve the conflicts?

@kiritigowda Resolved

**Pull request merged**
